export const CartActionTypes = {
    CART_DISPLAY_ALERT: 'SHOW_ALERT',
    CART_CLEAR_ALERT: 'CLEAR_ALERT',
    CART_ADD_ITEM: 'CART_ADD_ITEM',
    CART_REMOVE_ITEM: 'CART_REMOVE_ITEM',
    CART_CHANGE_ITEM_QTY: 'CART_CHANGE_ITEM_QTY',
    // CART_DECREASE_ITEM: 'CART_DECREASE_ITEM',
    CART_RESET: 'CART_RESET',
}
