export const ProductDetailsActionTypes = {
    PRODUCT_DETAILS_DISPLAY_ALERT: 'SHOW_ALERT',
    PRODUCT_DETAILS_CLEAR_ALERT: 'CLEAR_ALERT',
    PRODUCT_DETAILS_BEGIN: 'PRODUCT_DETAILS_BEGIN',
    PRODUCT_DETAILS_SUCCESS: 'PRODUCT_DETAILS_SUCCESS',
    PRODUCT_DETAILS_ERROR: 'PRODUCT_DETAILS_ERROR',
    PRODUCT_DETAILS_RESET: 'PRODUCT_DETAILS_RESET',
}
