export const ProductListActionTypes = {
    PRODUCT_LIST_DISPLAY_ALERT: 'SHOW_ALERT',
    PRODUCT_LIST_CLEAR_ALERT: 'CLEAR_ALERT',
    PRODUCT_LIST_BEGIN: 'PRODUCT_LIST_BEGIN',
    PRODUCT_LIST_SUCCESS: 'PRODUCT_LIST_SUCCESS',
    PRODUCT_LIST_ERROR: 'PRODUCT_LIST_ERROR',
    PRODUCT_LIST_SET_PAGE: 'PRODUCT_LIST_SET_PAGE',
    PRODUCT_LIST_CHANGE_TYPE: 'PRODUCT_LIST_CHANGE_TYPE',
    PRODUCT_LIST_RESET: 'PRODUCT_LIST_RESET',
}
