export const UserActionTypes = {
    USER_DISPLAY_ALERT: 'SHOW_ALERT',
    USER_CLEAR_ALERT: 'CLEAR_ALERT',
    SETUP_USER_BEGIN: 'SETUP_USER_BEGIN',
    SETUP_USER_SUCCESS: 'SETUP_USER_SUCCESS',
    SETUP_USER_ERROR: 'SETUP_USER_ERROR',
    LOGOUT_USER: 'LOGOUT_USER'
}
